PREDICT_EXAMPLES = """
Features:Granulocyte-to-lymphocyte ratio is 1.44, D-dimer is 0.19, chemotherapy, catheterization is CVC(Central Venous Catheter), no thoracic therapy, age at hospital is 29, platelet is 353.0, hemoglobin is 138.0, BMI is 18.83, gender is male, history of previous catheterization, no history of previous catheter related thrombosis, no lung cancer, no gastric cancer, lymphoma, no gynecologic tumors, no urologic tumors.

Disease Prediction: no catheter-related thrombosis 

Explanation:The GLR of the patients was 1.44. Some studies have suggested that GLR is associated with thrombosis, but the normal threshold value of GLR is still under debate and the range of normal values of GLR varies from study to study. The patient's GLR value of 1.44 was within the normal range, which may indicate a lower risk of thrombosis. The patient's D-dimer level was 0.19 mg/L, which is within the normal range (less than 0.5 mg/L is generally considered normal), and lower D-dimer levels are usually associated with lower thrombotic risk. The patient is receiving chemotherapy, a known risk factor for VTE. Chemotherapy patients have a 6.5-fold elevated risk of thrombosis. The patient is using a CVC (Central Venous Catheter). The use of a central venous catheter is itself a risk factor for VTE, especially in oncology patients. The patient was relatively young at 29 years of age, and usually younger patients have a lower risk of thrombosis. The patient's platelet level was 353.0, slightly above the normal range, and thrombocytosis is a predictor of VTE. The patient's hemoglobin level was 138.0 g/L, which is in the normal range.BMI: The patient's BMI was 18.83, which is in the underweight range, and it is generally accepted that higher BMIs are more likely to result in CRT.The patient was male, and the effect of gender on thrombotic risk has varied in different studies. The patient had a history of previous catheterization, which may increase the risk of CRT. The patient had no history of prior thrombosis and did not develop certain tumors, which may indicate a lower risk of thrombosis. In summary, the patient was predicted to have a low risk of CRT.


Features:Granulocyte-to-lymphocyte ratio is 2.73, D-dimer is 0.1, chemotherapy, catheterization is PICC(Peripherally Inserted Central Catheter), no thoracic therapy, age at hospital is 30, platelet is 267.0, hemoglobin is 108.0, BMI is 26.04, gender is female, no history of previous catheterization, no history of previous catheter related thrombosis, no lung cancer, no gastric cancer, no lymphoma, no gynecologic tumors, no urologic tumors.

Disease Prediction: catheter-related thrombosis

Explanation:GLR is an indicator of inflammation and immune status.GLR 2.73 is a relatively high value and may indicate the presence of an inflammatory response, which may be associated with an increased risk of thrombosis.D-dimer is a marker of coagulation and fibrinolysis.A level of 0.1 is usually considered normal or only slightly elevated and is not sufficient to directly diagnose VTE.Therefore, this level of D-dimer is unlikely to indicate the presence of CRT. chemotherapy may increase a patient's coagulation status because it can cause vascular endothelial injury and inflammation, which can increase the risk of thrombosis. the use of a PICC is a known risk factor for CRT because catheters can cause vascular endothelial injury and inflammation, which can promote thrombosis. Younger age is associated with a relatively lower risk of VTE. Platelet counts above the normal range may indicate a risk of inflammation or thrombosis. A slightly lower hemoglobin level may indicate mild anemia, but this level usually does not directly affect the risk of thrombosis. A slightly higher body mass index (BMI) indicates that the patient may be overweight, which is a risk factor for VTE. Gender is not an independent risk factor for CRT. There was no history of previous catheterization, which reduced the patient's risk of CRT. There is no history of catheter-related thrombosis, which reduces the patient's risk of CRT. No history of certain malignancies, which are known risk factors for VTE and CRT. In summary, the patient's risk of having catheter-related thrombosis is relatively high.
"""